### ISSUE TITLE
Most of the files in metadata/objects/ACAH/ are empty

### ISSUE THREAD

**Issue by FDenker** [Smithsonian/OpenAccess#5]
The only files with content that I could find are d2, b5, 62, 90, 6c, 3f, f4, 85, 8c and 9a inside the ACAH folder. The rest seem to be empty bz2 archives.

**Comment by andrewgunther** [comment]
There are stub files created for each hash prefix. Not all data sets have records that fall within the prefix. We'll review the process to see if perhaps we can remove the file if the set is empty. Thanks for you comment.
