### ISSUE TITLE
What do the folder names mean in ./metadata/objects?

### ISSUE THREAD

**Issue by lancejpollard** [Smithsonian/OpenAccess#8]
I am looking at https://github.com/Smithsonian/OpenAccess/tree/master/metadata/objects and can't find through search engines what these folders mean. Can you please explain or list their meaning?

Thank you!

**Comment by andrewgunther** [comment]
Lance,
Directories are divided into owning units (internal acronyms... AAA = Archives of American Art). I've reached out to the documentation folks at si to see where it is online. In the meantime I've added the code mappings to the README.md

**Comment by lancejpollard** [comment]
Thank you so much!

**Comment by lancejpollard** [comment]
Thank you so much!
